# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 02:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_caritem_sum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(upload_to=b'ad/%Y/%m', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xe8\xb7\xaf\xe5\xbe\x84'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='index',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\x8e\x92\xe5\x88\x97\xe9\xa1\xba\xe5\xba\x8f'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='index',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\x8e\x92\xe5\x88\x97\xe9\xa1\xba\xe5\xba\x8f'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, verbose_name=b'\xe5\x93\x81\xe7\x89\x8c\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Clothing', verbose_name=b'\xe8\xb4\xad\xe7\x89\xa9\xe8\xbd\xa6\xe4\xb8\xad\xe4\xba\xa7\xe5\x93\x81\xe6\x9d\xa1\xe7\x9b\xae'),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='sum_price',
            field=models.FloatField(default=0.0, verbose_name=b'\xe5\xb0\x8f\xe8\xae\xa1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=1, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe7\x9a\x84\xe6\x8e\x92\xe5\xba\x8f'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sex',
            field=models.IntegerField(default=0, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
        migrations.AlterField(
            model_name='category',
            name='typ',
            field=models.CharField(max_length=20, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\xa4\xa7\xe7\xb1\xbb'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Brand', verbose_name=b'\xe5\x93\x81\xe7\x89\x8c'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='desc',
            field=models.CharField(max_length=100, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='discount',
            field=models.FloatField(default=1, verbose_name=b'\xe6\x8a\x98\xe6\x89\xa3'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image_url_c',
            field=models.ImageField(default=b'clothing/ce.jpg', upload_to=b'clothing/%Y/%m', verbose_name=b'\xe8\xb4\xad\xe7\x89\xa9\xe8\xbd\xa6\xe5\xb1\x95\xe7\xa4\xba\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image_url_i',
            field=models.ImageField(default=b'clothing/default.jpg', upload_to=b'clothing/%Y/%m', verbose_name=b'\xe5\xb1\x95\xe7\xa4\xba\xe5\x9b\xbe\xe7\x89\x87\xe8\xb7\xaf\xe5\xbe\x84'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image_url_l',
            field=models.ImageField(default=b'clothing/default.jpg', upload_to=b'clothing/%Y/%m', verbose_name=b'\xe8\xaf\xa6\xe6\x83\x85\xe5\x9b\xbe\xe7\x89\x87\xe8\xb7\xaf\xe5\xbe\x841'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image_url_m',
            field=models.ImageField(default=b'clothing/default.jpg', upload_to=b'clothing/%Y/%m', verbose_name=b'\xe8\xaf\xa6\xe6\x83\x85\xe5\x9b\xbe\xe7\x89\x87\xe8\xb7\xaf\xe5\xbe\x842'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image_url_r',
            field=models.ImageField(default=b'clothing/default.jpg', upload_to=b'clothing/%Y/%m', verbose_name=b'\xe8\xaf\xa6\xe6\x83\x85\xe5\x9b\xbe\xe7\x89\x87\xe8\xb7\xaf\xe5\xbe\x843'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='name',
            field=models.CharField(max_length=30, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='new_price',
            field=models.FloatField(default=0.0, verbose_name=b'\xe7\x8e\xb0\xe4\xbb\xb7'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='num',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xba\x93\xe5\xad\x98'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='old_price',
            field=models.FloatField(default=0.0, verbose_name=b'\xe5\x8e\x9f\xe4\xbb\xb7'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='sales',
            field=models.IntegerField(default=0, verbose_name=b'\xe9\x94\x80\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.ManyToManyField(to='store.Size', verbose_name=b'\xe5\xb0\xba\xe5\xaf\xb8'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='tag',
            field=models.ManyToManyField(to='store.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
        migrations.AlterField(
            model_name='size',
            name='index',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\x8e\x92\xe5\x88\x97\xe9\xa1\xba\xe5\xba\x8f'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\xb0\xba\xe5\xaf\xb8'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'QQ\xe5\x8f\xb7\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
